package undercurrentcore.server.constants;

/**
 * Created by Niel on 10/16/2015.
 */
public enum ResponseTypes {

    EMPTY_REQUEST_PARAMETER,
    LOGIN_SUCCESSFUL,
    SERVER_ERROR,
    WORLD_TE_DOES_NOT_EXIST,
    USER_NOT_REGISTERED,
    CANT_RETRIEVE_USER_INFO,
    CANT_USE_FIELD,
    CANT_DO_TE_SWOP,
    NO_BLOCK_FOUND_FOR_INTERNAL_NAME,
    MISSING_BODY_MEMBER,
    ERROR_GETTING_TILE_UCTILEDEF,
    TE_NOT_IUCTILE,
    UCTILEDEF_IS_NULL,
    SPECIFIED_EDITABLEFIELD_NOT_EDITABLE,
    VALUE_NOT_VALID_FOR_FIELD,
    TE_UPDATE_SUCCESS
}
