package undercurrentcore.server.constants;

/**
 * Created by Niel on 10/16/2015.
 */
public enum ResponseTypes {

    EMPTY_REQUEST_PARAMETER,
    LOGIN_SUCCESSFUL,
    SERVER_ERROR,
    WORLD_TE_DOES_NOT_EXIST,
    USER_NOT_REGISTERED,
    CANT_USE_FIELD,
    NO_BLOCK_FOUND_FOR_INTERNAL_NAME,
    MISSING_BODY_MEMBER,
    ERROR_GETTING_TILE_EDITABLEFIELDS,
    MISSING_INVOKABLE_NAME,
    ERROR_GETTING_TILE_CUSTOMIVOKABLES,
    ERROR_WHILE_INVOKING_CUSTOMINVOKABLE,
    REQUEST_PARAMS_FOR_INVOKABLE_NOT_EQUAL_TO_NEEDED_AMOUNT,
    TE_NOT_IUCTILE,
    UCTILE_EDITABLEFIELDS_IS_NULL,
    UCTILE_CUSTOMINVOKABLES_IS_NULL,
    SPECIFIED_EDITABLEFIELD_NOT_EDITABLE,
    VALUE_NOT_VALID_FOR_FIELD,
    TE_UPDATE_SUCCESS
}
